# CI Self-Repair Loop
# 用法: .\scripts\ci-loop.ps1 [-MaxLoops 5] [-WaitMinutes 10]
# 循环检查 CI 状态，失败时收集上下文并写入文件，
# 下次打开 CodeBuddy session 时说"继续 CI 修复循环"即可。

param(
    [int]$MaxLoops = 5,
    [int]$WaitMinutes = 10
)

$GhExe = "${env:ProgramFiles}\GitHub CLI\gh.exe"
if (-not (Test-Path $GhExe)) {
    Write-Error "gh CLI not found at $GhExe"
    exit 1
}

$ContextFile = "$PSScriptRoot\..\.codebuddy\ci-loop-context.md"
$StateFile   = "$PSScriptRoot\..\.codebuddy\ci-loop-state.json"

function Write-Context($title, $status, $detail) {
    $content = @"
# CI Self-Repair Context (`$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`)

## Status: $status
## Last Run Title: $title

## Detail
$detail

---

> To continue, tell CodeBuddy: "**继续 CI 修复循环**"
> This context file was auto-generated by scripts/ci-loop.ps1
"@
    Set-Content -Path $ContextFile -Value $content -Encoding UTF8
    Write-Host "Context saved to $ContextFile" -ForegroundColor Green
}

function Get-State {
    if (Test-Path $StateFile) {
        return Get-Content $StateFile -Raw | ConvertFrom-Json
    }
    return @{ consecutiveFailures = 0; lastRunId = $null }
}

function Set-State($state) {
    $state | ConvertTo-Json | Set-Content $StateFile -Encoding UTF8
}

$state = Get-State
Write-Host "CI Loop started. Max loops: $MaxLoops, Wait: ${WaitMinutes}min" -ForegroundColor Cyan
Write-Host "Consecutive failures so far: $($state.consecutiveFailures)" -ForegroundColor Yellow

for ($i = 1; $i -le $MaxLoops; $i++) {
    Write-Host "`n=== Loop $i / $MaxLoops ===" -ForegroundColor Cyan

    # Fetch latest run
    $runs = & $GhExe run list --limit 1 --json databaseId,status,conclusion,displayTitle,createdAt 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host "gh CLI error: $runs" -ForegroundColor Red
        Start-Sleep -Seconds ($WaitMinutes * 60)
        continue
    }

    $run = $runs | ConvertFrom-Json
    $runId = $run.databaseId
    $title = $run.displayTitle
    $status = $run.status
    $conclusion = $run.conclusion

    Write-Host "Run $runId : $title"
    Write-Host "  status=$status conclusion=$conclusion"

    # Skip if same run we already processed
    if ($runId -eq $state.lastRunId) {
        Write-Host "  Same run, waiting for next..."
        Start-Sleep -Seconds ($WaitMinutes * 60)
        continue
    }

    if ($status -eq "in_progress" -or $status -eq "queued") {
        Write-Host "  CI still running, waiting ${WaitMinutes}min..."
        Start-Sleep -Seconds ($WaitMinutes * 60)
        continue
    }

    if ($conclusion -eq "success") {
        Write-Host "  CI PASSED!" -ForegroundColor Green
        $state.consecutiveFailures = 0
        Set-State $state
        Remove-Item $ContextFile -ErrorAction SilentlyContinue
        break
    }

    # Failure or cancelled
    $state.consecutiveFailures++
    $state.lastRunId = $runId
    Set-State $state

    # Get failed job info
    $jobs = & $GhExe run view $runId --json jobs --jq '.jobs[] | {name, status, conclusion, databaseId}' 2>&1 | ConvertFrom-Json
    $failedJob = $jobs | Where-Object { $_.conclusion -eq "failure" } | Select-Object -First 1

    if ($failedJob) {
        Write-Host "  Failed job: $($failedJob.name) (id=$($failedJob.databaseId))" -ForegroundColor Red

        # Get error log
        $log = & $GhExe run view $runId --log-failed --job $failedJob.databaseId 2>&1
        $errors = $log | Select-String -Pattern "Error|error|FAIL|Syntax error|exit code|failed" -CaseSensitive:$false | ForEach-Object { $_.Line }

        $detail = @"
### Run ID: $runId
### Failed Job: $($failedJob.name)

**Error excerpts:**
```
$($errors -join "`n")
```

**Consecutive failures:** $($state.consecutiveFailures)
"@

        Write-Context $title "FAILED" $detail
    }
    else {
        $detail = @"
### Run ID: $runId
### Conclusion: $conclusion
### Consecutive failures: $($state.consecutiveFailures)
"@
        Write-Context $title "$conclusion" $detail
    }

    Write-Host "  Context file updated. Open CodeBuddy and say '继续 CI 修复循环'." -ForegroundColor Yellow
    break
}

Write-Host "`nCI Loop finished." -ForegroundColor Cyan
